name: "Build SC2 Map"
description: "Build SC2 map using Python"
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build SC2 Map
      shell: bash
      run: |
        mkdir -p Output
        BASE="maps/${{ inputs.map%%_* }}"
        echo "Building map ${{ inputs.map }} from $BASE"
        python build_sc2map.py "$BASE" mods/Patch_5_0_14 mods/AiArenaExtraFixes "Output/${{ inputs.map}}"
      id: build_map

inputs:
  map:
    description: "Name of the SC2 map to build"
    required: true

outputs:
  output_path:
    description: "Where the built map was written"
    value: ${{ steps.build_map.outputs.output_path }}
